[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions-internal"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  framework = "nuxt"

[build.environment]
  NODE_VERSION = "20"
